"""Training pipeline for the k-factor residual prediction network.

Trains the KFactorResidualNet to predict corrections delta_2, delta_3,
delta_4 such that k_hat_i = k1 + delta_i approximates the true k_i.

Training loss:
    L = ||k_hat_2 - k2||^2 + ||k_hat_3 - k3||^2 + ||k_hat_4 - k4||^2

The target k-factors are generated by running classical RK4 on diverse
trajectories with varied initial conditions and ODE parameters.

GPU acceleration features:
    - Automatic Mixed Precision (AMP) with GradScaler for float16 training
    - torch.compile for kernel fusion (PyTorch 2.x)
    - GPU memory monitoring and timing

Usage:
    >>> trainer = KFactorTrainer(system, device=device)
    >>> model, history = trainer.train(n_trajectories=200, epochs=3000)
"""

from __future__ import annotations

import logging
import time
from typing import Dict, List, Tuple

import torch
import torch.nn as nn
from torch import Tensor
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, TensorDataset

from src.networks.k_factor_residual import KFactorResidualNet
from src.ode_systems import ODESystem
from src.training.data_generator import DataGenerator

logger = logging.getLogger(__name__)


class KFactorTrainer:
    """Training pipeline for the k-factor residual network.

    Handles data generation, model creation, training loop, and
    validation for the k-factor correction predictor.

    GPU features:
        - AMP (Automatic Mixed Precision) for 2-3× throughput on
          Tensor Cores.  Forward/backward in float16, master weights
          in float32 for numerical stability.
        - torch.compile for kernel fusion.
        - GPU memory monitoring during training.

    Attributes:
        system: ODE system to train on.
        device: Torch device for computation.
        generator: Data generator instance.
        use_amp: Whether AMP is available and enabled.

    Example:
        >>> system = get_system("damped_oscillator")
        >>> trainer = KFactorTrainer(system, device=torch.device("cuda"))
        >>> model, history = trainer.train(epochs=3000)
    """

    def __init__(
        self,
        system: ODESystem,
        device: torch.device | None = None,
    ):
        """Initialise the trainer.

        Args:
            system: ODE system defining the dynamics and parameter ranges.
            device: Torch device.  Auto-detects CUDA if available.
        """
        self.system = system
        self.device = device or torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )
        # Data generation always on CPU (sequential RK4, then transfer)
        self.generator = DataGenerator(system, device=torch.device("cpu"))
        # AMP is only beneficial on CUDA
        self.use_amp = self.device.type == "cuda"

        logger.info(
            "KFactorTrainer created: system='%s', device=%s, AMP=%s",
            system.name, self.device, self.use_amp,
        )
        if self.device.type == "cuda":
            logger.info(
                "GPU: %s | VRAM: %.1f GB",
                torch.cuda.get_device_name(self.device),
                torch.cuda.get_device_properties(self.device).total_memory / 1e9,
            )

    def train(
        self,
        n_trajectories: int = 200,
        dt: float = 0.01,
        epochs: int = 3000,
        batch_size: int = 512,
        lr: float = 1e-3,
        hidden_dim: int = 96,
        val_fraction: float = 0.2,
        use_compile: bool = True,
        lbfgs_steps: int = 50,
    ) -> Tuple[KFactorResidualNet, Dict[str, List[float]]]:
        """Train the k-factor residual network end-to-end.

        Steps:
            1. Generate training data (k1, y_n, t_n, h → k2, k3, k4) on CPU.
            2. Transfer to GPU, split into train/validation sets.
            3. Create the model, optimiser, AMP scaler, and optionally
               torch.compile the model.
            4. Training loop with AMP-wrapped forward pass + scaled gradients.
            5. Return trained model and loss history.

        Args:
            n_trajectories: Number of trajectories for data generation.
            dt: RK4 step size (also the ``h`` in training data).
            epochs: Number of training epochs.
            batch_size: Mini-batch size.
            lr: Initial learning rate for Adam.
            hidden_dim: Hidden layer width.
            val_fraction: Fraction of data held out for validation.
            use_compile: Whether to use ``torch.compile`` for kernel
                        fusion.  Requires PyTorch ≥ 2.0.
            lbfgs_steps: Number of L-BFGS fine-tuning steps after Adam.
                        Uses full-batch second-order optimisation with
                        strong Wolfe line search.  Set to 0 to disable.

        Returns:
            Tuple of (trained_model, history_dict).
        """
        train_start = time.time()

        # -- Step 1: Generate data on CPU -----------------------------------
        logger.info("Step 1/4: Generating k-factor training data on CPU...")
        data = self.generator.generate_k_factor_data(
            n_trajectories=n_trajectories, dt=dt,
        )

        n_total = len(data)
        n_val = int(n_total * val_fraction)
        n_train = n_total - n_val

        logger.info(
            "Data generated: %d total (%d train, %d val)",
            n_total, n_train, n_val,
        )

        # -- Step 2: Transfer to GPU, create data loaders -------------------
        logger.info("Step 2/4: Transferring data to %s...", self.device)
        perm = torch.randperm(n_total)
        train_idx = perm[:n_train]
        val_idx = perm[n_train:]

        # Compute residual targets: delta_i = k_i - k1
        delta_2_target = data.k2 - data.k1
        delta_3_target = data.k3 - data.k1
        delta_4_target = data.k4 - data.k1

        def make_loader(indices: Tensor, shuffle: bool = True) -> DataLoader:
            """Create a DataLoader with GPU-resident tensors.

            Args:
                indices: Sample indices to include.
                shuffle: Whether to shuffle batches.

            Returns:
                DataLoader with all tensors on ``self.device``.
            """
            dataset = TensorDataset(
                data.k1[indices].to(self.device),
                data.y_n[indices].to(self.device),
                data.t_n[indices].to(self.device),
                data.h[indices].to(self.device),
                data.theta_ode[indices].to(self.device),
                delta_2_target[indices].to(self.device),
                delta_3_target[indices].to(self.device),
                delta_4_target[indices].to(self.device),
            )
            return DataLoader(
                dataset, batch_size=batch_size, shuffle=shuffle,
            )

        train_loader = make_loader(train_idx, shuffle=True)
        val_loader = make_loader(val_idx, shuffle=False)

        # -- Step 3: Create model + GPU optimisations -----------------------
        logger.info("Step 3/4: Creating k-factor model on %s...", self.device)
        model = KFactorResidualNet(
            state_dim=self.system.dim,
            param_dim=len(self.system.param_names),
            hidden_dim=hidden_dim,
        ).to(self.device)

        # Optionally compile for kernel fusion
        import platform
        train_model = model
        if use_compile and self.device.type == "cuda" and platform.system() != "Windows":
            # torch.compile uses Triton backend which is Linux-only.
            # On Windows, we fall back to eager mode (still GPU-accelerated).
            try:
                train_model = torch.compile(model)
                logger.info("torch.compile applied for kernel fusion")
            except Exception as exc:
                logger.warning("torch.compile failed (%s), using eager mode", exc)
                train_model = model
        elif use_compile and platform.system() == "Windows":
            logger.info("torch.compile skipped (Triton unavailable on Windows)")

        optimiser = torch.optim.Adam(model.parameters(), lr=lr)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimiser, T_max=epochs, eta_min=lr * 0.01,
        )
        mse_loss = nn.MSELoss()

        # AMP: GradScaler for stable float16 training
        scaler = GradScaler(self.device.type, enabled=self.use_amp)

        if self.use_amp:
            logger.info("AMP enabled: float16 forward pass + float32 master weights")

        # -- Step 4: Training loop with AMP ---------------------------------
        logger.info("Step 4/4: Training for %d epochs...", epochs)
        history: Dict[str, List[float]] = {"train_loss": [], "val_loss": []}

        for epoch in range(epochs):
            # ---- Training ----
            model.train()
            epoch_loss = 0.0
            n_batches = 0

            for k1, y_n, t_n, h, theta, d2_true, d3_true, d4_true in train_loader:
                optimiser.zero_grad(set_to_none=True)

                # AMP: forward pass in float16 on GPU
                with autocast(device_type=self.device.type, enabled=self.use_amp):
                    d2_pred, d3_pred, d4_pred = train_model(k1, y_n, t_n, h, theta)
                    loss = (
                        mse_loss(d2_pred, d2_true)
                        + mse_loss(d3_pred, d3_true)
                        + mse_loss(d4_pred, d4_true)
                    )

                # AMP: scale loss, backward, unscale, step
                scaler.scale(loss).backward()
                scaler.step(optimiser)
                scaler.update()

                epoch_loss += loss.item()
                n_batches += 1

            scheduler.step()
            avg_train_loss = epoch_loss / max(n_batches, 1)
            history["train_loss"].append(avg_train_loss)

            # ---- Validation ----
            model.eval()
            val_loss = 0.0
            n_val_batches = 0

            with torch.no_grad():
                for k1, y_n, t_n, h, theta, d2_true, d3_true, d4_true in val_loader:
                    with autocast(device_type=self.device.type, enabled=self.use_amp):
                        d2_p, d3_p, d4_p = train_model(k1, y_n, t_n, h, theta)
                        val_loss += (
                            mse_loss(d2_p, d2_true)
                            + mse_loss(d3_p, d3_true)
                            + mse_loss(d4_p, d4_true)
                        ).item()
                    n_val_batches += 1

            avg_val_loss = val_loss / max(n_val_batches, 1)
            history["val_loss"].append(avg_val_loss)

            if epoch % 50 == 0 or epoch == epochs - 1:
                # GPU memory logging
                mem_info = ""
                if self.device.type == "cuda":
                    mem_used = torch.cuda.memory_allocated(self.device) / 1e6
                    mem_reserved = torch.cuda.memory_reserved(self.device) / 1e6
                    mem_info = f", GPU_mem={mem_used:.0f}/{mem_reserved:.0f}MB"

                logger.info(
                    "Epoch %d/%d: train=%.6f, val=%.6f, lr=%.2e%s",
                    epoch, epochs, avg_train_loss, avg_val_loss,
                    scheduler.get_last_lr()[0], mem_info,
                )

        # -- Stage 2: L-BFGS fine-tuning (hybrid optimizer) ------------------
        if lbfgs_steps > 0:
            logger.info(
                "L-BFGS fine-tuning: %d steps (lr=1.0, history=10, "
                "strong_wolfe)...",
                lbfgs_steps,
            )

            # Full-batch training data for L-BFGS
            fk1 = data.k1[train_idx].to(self.device)
            fy_n = data.y_n[train_idx].to(self.device)
            ft_n = data.t_n[train_idx].to(self.device)
            fh = data.h[train_idx].to(self.device)
            ftheta = data.theta_ode[train_idx].to(self.device)
            fd2 = delta_2_target[train_idx].to(self.device)
            fd3 = delta_3_target[train_idx].to(self.device)
            fd4 = delta_4_target[train_idx].to(self.device)

            # Full-batch validation data
            vk1 = data.k1[val_idx].to(self.device)
            vy_n = data.y_n[val_idx].to(self.device)
            vt_n = data.t_n[val_idx].to(self.device)
            vh = data.h[val_idx].to(self.device)
            vtheta = data.theta_ode[val_idx].to(self.device)
            vd2 = delta_2_target[val_idx].to(self.device)
            vd3 = delta_3_target[val_idx].to(self.device)
            vd4 = delta_4_target[val_idx].to(self.device)

            lbfgs = torch.optim.LBFGS(
                model.parameters(),
                lr=1.0,
                history_size=10,
                max_iter=20,
                line_search_fn="strong_wolfe",
            )

            model.train()
            for step in range(lbfgs_steps):
                def closure():
                    lbfgs.zero_grad()
                    d2p, d3p, d4p = model(fk1, fy_n, ft_n, fh, ftheta)
                    loss = (
                        mse_loss(d2p, fd2)
                        + mse_loss(d3p, fd3)
                        + mse_loss(d4p, fd4)
                    )
                    loss.backward()
                    return loss

                loss = lbfgs.step(closure)
                lbfgs_train = loss.item()
                history["train_loss"].append(lbfgs_train)

                model.eval()
                with torch.no_grad():
                    vd2p, vd3p, vd4p = model(vk1, vy_n, vt_n, vh, vtheta)
                    lbfgs_val = (
                        mse_loss(vd2p, vd2)
                        + mse_loss(vd3p, vd3)
                        + mse_loss(vd4p, vd4)
                    ).item()
                history["val_loss"].append(lbfgs_val)
                model.train()

                if step % 10 == 0 or step == lbfgs_steps - 1:
                    mem_info = ""
                    if self.device.type == "cuda":
                        mem_used = torch.cuda.memory_allocated(self.device) / 1e6
                        mem_reserved = torch.cuda.memory_reserved(self.device) / 1e6
                        mem_info = f", GPU_mem={mem_used:.0f}/{mem_reserved:.0f}MB"
                    logger.info(
                        "L-BFGS %d/%d: train=%.6f, val=%.6f%s",
                        step, lbfgs_steps, lbfgs_train, lbfgs_val, mem_info,
                    )

            del fk1, fy_n, ft_n, fh, ftheta, fd2, fd3, fd4
            del vk1, vy_n, vt_n, vh, vtheta, vd2, vd3, vd4

        total_time = time.time() - train_start
        logger.info("Training complete! Total time: %.1fs (%.1f min)",
                     total_time, total_time / 60)
        logger.info(
            "Final: train_loss=%.6f, val_loss=%.6f",
            history["train_loss"][-1], history["val_loss"][-1],
        )

        return model, history
