"""Training pipeline for the k-factor residual prediction network.

Trains the KFactorResidualNet to predict corrections delta_2, delta_3,
delta_4 such that k_hat_i = k1 + delta_i approximates the true k_i.

Training loss:
    L = ||k_hat_2 - k2||^2 + ||k_hat_3 - k3||^2 + ||k_hat_4 - k4||^2

The target k-factors are generated by running classical RK4 on diverse
trajectories with varied initial conditions and ODE parameters.

Usage:
    >>> trainer = KFactorTrainer(system, device=device)
    >>> model, history = trainer.train(n_trajectories=200, epochs=3000)
"""

from __future__ import annotations

import logging
from typing import Dict, List, Tuple

import torch
import torch.nn as nn
from torch import Tensor
from torch.utils.data import DataLoader, TensorDataset

from src.networks.k_factor_residual import KFactorResidualNet
from src.ode_systems import ODESystem
from src.training.data_generator import DataGenerator

logger = logging.getLogger(__name__)


class KFactorTrainer:
    """Training pipeline for the k-factor residual network.

    Handles data generation, model creation, training loop, and
    validation for the k-factor correction predictor.

    Attributes:
        system: ODE system to train on.
        device: Torch device for computation.
        generator: Data generator instance.

    Example:
        >>> system = get_system("damped_oscillator")
        >>> trainer = KFactorTrainer(system)
        >>> model, history = trainer.train(epochs=3000)
    """

    def __init__(
        self,
        system: ODESystem,
        device: torch.device | None = None,
    ):
        """Initialise the trainer.

        Args:
            system: ODE system defining the dynamics and parameter ranges.
            device: Torch device.  Defaults to CPU.
        """
        self.system = system
        self.device = device or torch.device("cpu")
        self.generator = DataGenerator(system, device=torch.device("cpu"))

        logger.info(
            "KFactorTrainer created for system='%s' on device=%s",
            system.name, self.device,
        )

    def train(
        self,
        n_trajectories: int = 200,
        dt: float = 0.01,
        epochs: int = 3000,
        batch_size: int = 512,
        lr: float = 1e-3,
        hidden_dim: int = 96,
        val_fraction: float = 0.2,
    ) -> Tuple[KFactorResidualNet, Dict[str, List[float]]]:
        """Train the k-factor residual network end-to-end.

        Steps:
            1. Generate training data (k1, y_n, t_n, h → k2, k3, k4).
            2. Split into train/validation sets.
            3. Create the model and optimiser.
            4. Training loop with MSE loss on residuals.
            5. Return trained model and loss history.

        Args:
            n_trajectories: Number of trajectories for data generation.
            dt: RK4 step size (also the ``h`` in training data).
            epochs: Number of training epochs.
            batch_size: Mini-batch size.
            lr: Initial learning rate for Adam.
            hidden_dim: Hidden layer width.
            val_fraction: Fraction of data held out for validation.

        Returns:
            Tuple of (trained_model, history_dict).
        """
        # -- Step 1: Generate data ------------------------------------------
        logger.info("Step 1/4: Generating k-factor training data...")
        data = self.generator.generate_k_factor_data(
            n_trajectories=n_trajectories, dt=dt,
        )

        n_total = len(data)
        n_val = int(n_total * val_fraction)
        n_train = n_total - n_val

        logger.info(
            "Data generated: %d total (%d train, %d val)",
            n_total, n_train, n_val,
        )

        # -- Step 2: Create data loaders ------------------------------------
        perm = torch.randperm(n_total)
        train_idx = perm[:n_train]
        val_idx = perm[n_train:]

        # Compute residual targets: delta_i = k_i - k1
        delta_2_target = data.k2 - data.k1
        delta_3_target = data.k3 - data.k1
        delta_4_target = data.k4 - data.k1

        def make_loader(indices: Tensor) -> DataLoader:
            """Create a DataLoader from selected indices."""
            dataset = TensorDataset(
                data.k1[indices].to(self.device),
                data.y_n[indices].to(self.device),
                data.t_n[indices].to(self.device),
                data.h[indices].to(self.device),
                delta_2_target[indices].to(self.device),
                delta_3_target[indices].to(self.device),
                delta_4_target[indices].to(self.device),
            )
            return DataLoader(dataset, batch_size=batch_size, shuffle=True)

        train_loader = make_loader(train_idx)
        val_loader = make_loader(val_idx)

        # -- Step 3: Create model -------------------------------------------
        logger.info("Step 2/4: Creating k-factor model...")
        model = KFactorResidualNet(
            state_dim=self.system.dim,
            hidden_dim=hidden_dim,
        ).to(self.device)

        optimiser = torch.optim.Adam(model.parameters(), lr=lr)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimiser, T_max=epochs, eta_min=lr * 0.01,
        )
        mse_loss = nn.MSELoss()

        # -- Step 4: Training loop ------------------------------------------
        logger.info("Step 3/4: Training for %d epochs...", epochs)
        history = {"train_loss": [], "val_loss": []}

        for epoch in range(epochs):
            # Training
            model.train()
            epoch_loss = 0.0
            n_batches = 0

            for k1, y_n, t_n, h, d2_true, d3_true, d4_true in train_loader:
                optimiser.zero_grad(set_to_none=True)

                d2_pred, d3_pred, d4_pred = model(k1, y_n, t_n, h)

                loss = (
                    mse_loss(d2_pred, d2_true)
                    + mse_loss(d3_pred, d3_true)
                    + mse_loss(d4_pred, d4_true)
                )

                loss.backward()
                optimiser.step()

                epoch_loss += loss.item()
                n_batches += 1

            scheduler.step()
            avg_train_loss = epoch_loss / max(n_batches, 1)
            history["train_loss"].append(avg_train_loss)

            # Validation
            model.eval()
            val_loss = 0.0
            n_val_batches = 0

            with torch.no_grad():
                for k1, y_n, t_n, h, d2_true, d3_true, d4_true in val_loader:
                    d2_p, d3_p, d4_p = model(k1, y_n, t_n, h)
                    val_loss += (
                        mse_loss(d2_p, d2_true)
                        + mse_loss(d3_p, d3_true)
                        + mse_loss(d4_p, d4_true)
                    ).item()
                    n_val_batches += 1

            avg_val_loss = val_loss / max(n_val_batches, 1)
            history["val_loss"].append(avg_val_loss)

            if epoch % 500 == 0 or epoch == epochs - 1:
                logger.info(
                    "Epoch %d/%d: train_loss=%.6f, val_loss=%.6f, lr=%.2e",
                    epoch, epochs, avg_train_loss, avg_val_loss,
                    scheduler.get_last_lr()[0],
                )

        logger.info("Step 4/4: Training complete!")
        logger.info(
            "Final: train_loss=%.6f, val_loss=%.6f",
            history["train_loss"][-1], history["val_loss"][-1],
        )

        return model, history
